name: Task Silo Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'task-silo-service/**'
      - 'shared-lib/**'
      - '.github/workflows/task-silo-service-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'task-silo-service/**'
      - 'shared-lib/**'
      - '.github/workflows/task-silo-service-ci.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test parent nucleus
        run: mvn clean install -U

      - name: Build and test shared-lib
        run: mvn -B clean install -pl shared-lib

      - name: Build and test task-silo-service
        run: mvn -B clean test -pl task-silo-service

      - name: Build JAR
        run: mvn -B package -pl task-silo-service -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to EC2
        env:
          TASK_SILO_SERVICE_EC2_HOST: ${{ secrets.TASK_SILO_SERVICE_EC2_HOST }}
          TASK_SILO_SERVICE_EC2_PEM: ${{ secrets.TASK_SILO_SERVICE_EC2_PEM }}
        run: |
          chmod +x task-silo-service/scripts/deploy-ec2.sh
          task-silo-service/scripts/deploy-ec2.sh