server:
  port: 8080

spring:
  application:
    name: task-silo-service
  datasource:
    url: jdbc:postgresql://mytest.culss6gmw8na.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Sindhuj12
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      validation-timeout: 3000
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd HH:mm:ss

debug: true
logging:
  level:
    root: INFO
    com.algobrewery: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: mappings,health,info,metrics
  endpoint:
    mappings:
      enabled: true

outbounds:
  user-service:
    url: http://52.23.186.179:8080
    timeout: 5000
